version: '3.4'

services:
  cleanmovie.ui:
    image: ${DOCKER_REGISTRY-}cleanmovieui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:443"
      - "5000:80"
    build:
      context: .
      dockerfile: CleanMovie.UI/Dockerfile

  cleanmovie.api:
    image: ${DOCKER_REGISTRY-}cleanmovieapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8084:80"
      # - "8085:443"
    build:
      context: .
      dockerfile: CleanMovie.API/Dockerfile
    # volumes:
    #   - ~/.aspnet/https:/root/.aspnet/https:ro
    #   - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro