name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '24 3 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_CLEAN_BLAZOR_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_CLEAN_BLAZOR_PASSWORD }}          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Build and push Web API
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./CleanMovie.API/Dockerfile
          tags: sutin1990docker/cleanmovieapi:tagname1
          
      -
        name: Build and push Web UI
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./CleanMovie.UI/Dockerfile
          tags: sutin1990docker/cleanmovieui:tagname1
