name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '24 3 * * *'
  push:
    branches: [ develop ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ develop ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Run docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "/docker-compose.yml"
          down-flags: "--volumes"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_CLEAN_BLAZOR_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_CLEAN_BLAZOR_PASSWORD }}
      -
        name: Build and push Web API
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sutin1990docker/cleanmovieapi:tagname1
